name: twasol_ai
description: Realtime chat app (groups + DMs) using Flutter + Firebase with FCM notifications & contacts sync.
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  intl: ^0.20.2
  emoji_picker_flutter: ^2.2.0
  # Local storage
  shared_preferences: ^2.5.3
  # Firebase (أبقيناها مرنة لتفادي تعارض النسخ في بيئتك الحالية)
  firebase_core: ^2.25.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_messaging: ^14.7.15
  # (اختياري للمرفقات لاحقًا)
  firebase_storage: ^11.6.5

  # Notifications (محلية) + الأذونات
  flutter_local_notifications: ^19.4.1
  permission_handler: ^12.0.1

  # Contacts (بديل حديث لـ contacts_service)
  flutter_contacts: ^1.1.9+2

  # (اختياري للصور لاحقًا)
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  path_provider: ^2.1.5

  http: ^1.2.2
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  # فعّل هذا القسم عند إضافة موارد ثابتة
  # assets:
  #   - assets/
