import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';
import 'common/theme.dart';
import 'features/chat/data/chat_repository.dart';
import 'features/auth/presentation/login_page.dart';
import 'firebase_options.dart'; // Will be generated by flutterfire configure

import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  late final ChatRepository _repo;
  late final Future<void> _initFuture;

  @override
  void initState() {
    super.initState();
    _repo = ChatRepository(FirebaseAuth.instance, FirebaseFirestore.instance);
    _initFuture = _init();
  }

  Future<void> _init() async {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    await _repo.init();
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      future: _initFuture,
      builder: (context, snapshot) {
        if (snapshot.connectionState != ConnectionState.done) {
          return const MaterialApp(home: Scaffold(body: Center(child: CircularProgressIndicator())));
        }
        return ChangeNotifierProvider.value(
          value: _repo,
          child: MaterialApp(
            debugShowCheckedModeBanner: false,
            title: 'Flutter Messenger (Firebase)',
            theme: appTheme(),
            home: const LoginPage(),
          ),
        );
      },
    );
  }
}
