// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACEABg7nBM0UpprrKozRZMromtzc6Y5SM',
    appId: '1:776894109088:web:67ac1d863053ddf96cc0c5',
    messagingSenderId: '776894109088',
    projectId: 'twasol-5acdb',
    authDomain: 'twasol-5acdb.firebaseapp.com',
    storageBucket: 'twasol-5acdb.firebasestorage.app',
    measurementId: 'G-DT7MGQEWRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCklntuzVG8mI-VUZSspMx7xuUASUWftSM',
    appId: '1:776894109088:android:c82772f10fe21a626cc0c5',
    messagingSenderId: '776894109088',
    projectId: 'twasol-5acdb',
    storageBucket: 'twasol-5acdb.firebasestorage.app',
  );
}
